<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2 (Python 3.8.2 on win32)" generated="20200428 09:27:17.229" rpa="false">
<suite id="s1" name="ExtResTC1" source="C:\development\robot-scripts\MyProgram\Tests\ExtResource\ExtResTC1.robot">
<test id="s1-t1" name="Test Case 1">
<kw name="Run Keyword" library="BuiltIn">
<doc>Executes the given keyword with the given arguments.</doc>
<arguments>
<arg>Keyword2</arg>
</arguments>
<kw name="Keyword2">
<msg timestamp="20200428 09:27:17.305" level="FAIL">No keyword with name 'Keyword2' found. Did you mean:
    BuiltIn.Run Keyword</msg>
<status status="FAIL" starttime="20200428 09:27:17.304" endtime="20200428 09:27:17.305"></status>
</kw>
<status status="FAIL" starttime="20200428 09:27:17.301" endtime="20200428 09:27:17.305"></status>
</kw>
<status status="FAIL" starttime="20200428 09:27:17.300" endtime="20200428 09:27:17.305" critical="yes">No keyword with name 'Keyword2' found. Did you mean:
    BuiltIn.Run Keyword</status>
</test>
<status status="FAIL" starttime="20200428 09:27:17.237" endtime="20200428 09:27:17.307"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="ExtResTC1">ExtResTC1</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20200428 09:27:17.297" level="ERROR">Error in file 'C:\development\robot-scripts\MyProgram\Tests\ExtResource\ExtResTC1.robot' on line 2: Resource file '..\Tests\ExtResource\UserKeywords.robot' does not exist.</msg>
</errors>
</robot>
